# Generated by Django 5.2.7 on 2025-10-31 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва технології')),
            ],
            options={
                'verbose_name': 'Технологія',
                'verbose_name_plural': 'Технології',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Навчальний заклад')),
                ('degree', models.CharField(max_length=100, verbose_name='Ступінь')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Спеціальність')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='users.userprofile', verbose_name='Профіль')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('role', models.CharField(max_length=100, verbose_name='Посада')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Опис обов'язків")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='users.userprofile', verbose_name='Профіль')),
            ],
            options={
                'verbose_name': 'Досвід роботи',
                'verbose_name_plural': 'Досвід роботи',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва проекту')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Зображення')),
                ('github_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Посилання на GitHub')),
                ('live_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Посилання на сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.userprofile', verbose_name='Профіль')),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology', verbose_name='Технології')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
                'ordering': ['-created_at'],
            },
        ),
    ]
