# Generated by Django 5.2.7 on 2025-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Перегляди'),
        ),
    ]
