# Generated by Django 5.2.7 on 2025-12-29 18:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.unique_profile_pic_path, verbose_name='Фото профілю'),
        ),
    ]
